[options]

# 📂 Datos persistentes
data_dir = /var/lib/odoo

# 🔌 Addons (solo si montás el volumen)
addons_path = /mnt/extra-addons

# 📝 Logs
logfile = /var/log/odoo/odoo.log

smtp_server = smtp.gmail.com
smtp_port = 587
smtp_user = leonobitech@gmail.com
smtp_password = bwey gojg hcyn goly
smtp_from = leonobitech@gmail.com
smtp_ssl = False
smtp_tls = True