[options]
# 📂 Datos persistentes
data_dir = /var/lib/odoo

# 🔌 Addons futuros
addons_path = /mnt/extra-addons

# Database Manager
admin_passwd = iGNjHHHuBrY-vy2

 # 🏢 Base de datos Postgres
db_host = postgres_odoo
db_port = 5432
db_user = odoo
db_password = G1OpNWgcikqbttQeSQ8XHw6iamN8wOZ0moRHNIiv5TtQw5ZpDHIUWkCW50ogkhPu0A

smtp_server = smtp.gmail.com
smtp_port = 587
smtp_user = leonobitech@gmail.com
smtp_password = bwey gojg hcyn goly
smtp_from = leonobitech@gmail.com
smtp_ssl = False
smtp_tls = True