[options]
# 📂 Datos persistentes
data_dir = /var/lib/odoo

# 🔌 Addons futuros
addons_path = /mnt/extra-addons

# 🗄️ Base de datos
db_host = ${POSTGRES_HOST_ODOO}
db_port = ${POSTGRES_PORT_ODOO}
db_user = ${POSTGRES_USER_ODOO}
db_password = ${POSTGRES_PASSWORD_ODOO}