# ./traefik/traefik.yml
# 🌐 Traefik static configuration

log:
  level: INFO  # Cambiar a DEBUG si necesitás depurar

api:
  dashboard: true
  insecure: false  # ✅ Siempre en false en producción

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https  # 🔐 Redirecciona todo HTTP a HTTPS

  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true         # opcional, permite headers aún si no vienen de trustedIPs
      trustedIPs:
        - "173.245.48.0/20"
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "141.101.64.0/18"
        - "108.162.192.0/18"
        - "190.93.240.0/20"
        - "188.114.96.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "162.158.0.0/15"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
        - "172.64.0.0/13"
        - "131.0.72.0/22"

providers:
  docker:
    exposedByDefault: false  # ✅ Solo servicios con traefik.enable=true

  file:
    filename: /etc/traefik/dynamic/middlewares.yaml  # 🔧 Middlewares dinámicos
    watch: true  # 🔄 Recarga automática al editar el archivo

certificatesResolvers:
  le:
    acme:
      email: ${SSL_EMAIL}
      storage: /acme.json
      httpChallenge:
        entryPoint: web  # 🌍 Realiza desafío HTTP en puerto 80
