server {
    listen 80;

    location /media/ {
        alias /baserow/media/;
        autoindex off;
        access_log off;

        add_header X-Served-By Baserow-Media;
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header X-Content-Type-Options nosniff;
        add_header Referrer-Policy no-referrer;

        try_files $uri $uri/ =404;
    }
}