server {
    listen 80;

    location /media/ {
        alias /baserow/media/;
        autoindex off;
        access_log off;
        add_header X-Served-By Baserow-Media;
        try_files $uri $uri/ =404;
    }
}