export const ERROR_CODE = {
  BAD_REQUEST: "BadRequest",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  REFRESH_TOKEN_MISSING: "RefreshTokenMissing",
  ACCESS_DENIED: "AccessDenied",
  ACCESS_TOKEN_REQUIRED: "AccesToekenRequired",
  ACCESS_KEYS_REQUIRED: "AccesKeysRequired",
  INVALID_CLIENT_KEY: "InvalidClientKey",
  CLIENT_KEY_REQUIRED: "ClientKeyRequired",
  FINGERPRINT_MISMATCH: "FingerprintMismatch",
  INVALID_CREDENTIALS: "Credenciales inválidas",
  EMAIL_NOT_VERIFIED: "Debes verificar tu email antes de iniciar sesión",
  INVALID_REFRESH_TOKEN: "InvalidRefreshToken",
  INVALID_ACCESS_TOKEN: "InvalidAccessToken",
  INVALID_TOKEN: "InvalidToken",
  INVALID_AUDIENCE: "InvalidAudience",
  INVALID_TOKEN_STRUCTURE: "InvalidTokenStructure",
  INVALID_CLAIMS: "InvalidClaims",
  INVALID_PAYLOAD_STRUCTURE: "InvalidPayloadStructure",
  INVALID_OR_EXPIRED_TOKEN: "InvalidOrExpiredToken",
  INVALID_SESSION: "InvalidSession",
  INVALID_INPUT: "InvalidInput",
  INVALID_OR_EXPIRED_SESSION: "InvalidOrExpiredTSession",
  NOT_FOUND: "NotFound",
  USER_NOT_FOUND: "UserNotFound",
  TOKEN_NOT_FOUND: "TokenNotFound",
  UNRECOGNIZED_TOKEN: "UnrecognizedToken",
  TOKEN_EXPIRED: "TokenExpired",
  TOKEN_REVOKED: "TokenRevoked",
  TOKEN_MISSING: "TokenMissing",
  INVALID_SIGNATURE: "InvalidSignature",
  SESSION_NOT_FOUND: "SessionNotFound",
  REVOKED_SESSION: "RevokedSession",
  SESSION_NOT_FOUND_WITH_USER: "SessionNotFoundWithUser",
  SESSION_NOT_FOUND_WITH_USER_ACTIVE: "SessionNotFoundWithUserActive",
  SESSION_EXPIRED: "SessionExpired",
  CANNOT_DELETE_CURRENT_SESSION: "CannotDeleteCurrentSession",
  CONFLICT: "Conflict",
  ALREADY_VERIFIED: "AlreadyVerified",
  CODE_EXPIRED: "CodeExpired",
  USER_NOT_VERIFICATED: "UserNotVerificated",
  NO_AVAILABLE_CODE: "NoAvailableCode",
  INVALID_CODE: "InvalidCode",
  DEVICE_ALREADY_EXISTS: "DeviceAlreadyExists",
  PASSWORD_REUSE: "PasswordReuse",
  INVALID_OR_EXPIRED_CODE: "InvalidOrExpiredCode",
  VERIFICATION_CODE_NOT_FOUND: "VerificationCodeNotFound",
  INVALID_VERIFICATION_CODE: "InvalidVerificationCode",
  UNPROCESSABLE_CONTENT: "UnprocessableContent",
  TOO_MANY_REQUESTS: "TooManyRequests",
  INTERNAL_SERVER_ERROR: "InternalServerError",
  REDIS_ERROR: "RedisIsUnavailable",
  SERVICE_UNAVAILABLE: "ServiceUnavailable",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
