/**
 * WebSocket Protocol Types for IoT Light Control
 *
 * Messages flow:
 * - Dashboard -> Backend -> Device (commands)
 * - Device -> Backend -> Dashboard (state/telemetry)
 */

// =============================================================================
// Dashboard -> Device Messages (via Backend)
// =============================================================================

export interface SetLightMessage {
  type: "set_light";
  intensity: number; // 0-100
  temperature: number; // 0-100 (0=warm, 100=cool)
}

export interface SetModeMessage {
  type: "set_mode";
  mode: "manual" | "auto";
}

export interface SyncScheduleMessage {
  type: "sync_schedule";
  schedule: SchedulePoint[];
}

export interface RequestStateMessage {
  type: "request_state";
}

export interface PingMessage {
  type: "ping";
  timestamp: number;
}

export interface CommandMessage {
  type: "command";
  commandId?: string; // Generated by backend when routing
  action: string; // "restart" | "get_status" | "led_on" | "led_off" | custom
  params?: Record<string, unknown>;
}

// =============================================================================
// Device -> Dashboard Messages (via Backend)
// =============================================================================

export interface LightStateMessage {
  type: "light_state";
  deviceId: string;
  intensity: number;
  temperature: number;
  mode: "manual" | "auto";
}

export interface TelemetryMessage {
  type: "telemetry";
  deviceId: string;
  freeHeap: number;
  wifiRssi: number;
  uptimeSecs: number;
  timestamp: number;
  localTime?: string; // ESP32 local time "YYYY-MM-DD HH:MM:SS" (from NTP)
}

export interface AckMessage {
  type: "ack";
  deviceId: string;
  messageId?: string;
  success: boolean;
  error?: string;
}

export interface PongMessage {
  type: "pong";
  deviceId: string;
  timestamp: number;
  serverTimestamp: number;
}

export interface CommandAckMessage {
  type: "command_ack";
  deviceId: string;
  commandId: string;
  action: string;
  success: boolean;
  result?: Record<string, unknown>;
  error?: string;
}

export interface DeviceConnectedMessage {
  type: "device_connected";
  deviceId: string;
}

export interface DeviceDisconnectedMessage {
  type: "device_disconnected";
  deviceId: string;
}

// =============================================================================
// Backend -> Client Messages
// =============================================================================

export interface ErrorMessage {
  type: "error";
  code: string;
  message: string;
}

export interface WelcomeMessage {
  type: "welcome";
  connectionId: string;
  serverTime: number;
}

export interface SessionExpiredMessage {
  type: "session_expired";
  reason: "token_expired" | "session_revoked" | "logout";
}

// =============================================================================
// Schedule Types
// =============================================================================

export interface SchedulePoint {
  hour: number; // 0-23
  minute: number; // 0-59
  intensity: number; // 0-100
  temperature: number; // 0-100
}

// =============================================================================
// Union Types
// =============================================================================

export type DashboardToDeviceMessage =
  | SetLightMessage
  | SetModeMessage
  | SyncScheduleMessage
  | RequestStateMessage
  | PingMessage
  | CommandMessage;

export type DeviceToDashboardMessage =
  | LightStateMessage
  | TelemetryMessage
  | AckMessage
  | PongMessage
  | CommandAckMessage;

export type ServerMessage =
  | ErrorMessage
  | WelcomeMessage
  | DeviceConnectedMessage
  | DeviceDisconnectedMessage
  | SessionExpiredMessage;

export type WsMessage =
  | DashboardToDeviceMessage
  | DeviceToDashboardMessage
  | ServerMessage;

// =============================================================================
// Connection Types
// =============================================================================

export type ConnectionType = "device" | "dashboard";

export interface DeviceConnection {
  type: "device";
  deviceId: string;
  dbId: string; // MongoDB ObjectId
  connectedAt: Date;
}

export interface DashboardConnection {
  type: "dashboard";
  userId: string;
  subscribedDevices: Set<string>; // deviceIds watching
  connectedAt: Date;
}

export type ConnectionInfo = DeviceConnection | DashboardConnection;
